### ISSUE TITLE
Feature Request: autowrap per filetype

### ISSUE THREAD

**Issue by wevre** [stkb/Rewrap#149]
Allow the `rewrap.autowrap.enabled` setting to be specified on a per filetype basis.

I'd love to be able to turn it off, for example, for some filetypes, but otherwise leave it on globally.

    "rewrap.autoWrap.enabled": true,
    "[xml]": {
        "rewrap.autoWrap.enabled": false,
    }

**Comment by memeplex** [comment]
I wanted to asked this too but I settled down on a more modest proposal: https://github.com/stkb/Rewrap/issues/142

The fact that a soft-wrapping document could be silently being hard-wrapped should be fixed. The wrap column is common to both kind of wrapping so it's difficult to spot this is happening.

**Comment by aleclarson** [comment]
It's kinda weird that this doesn't work OOTB. Is there some special VSCode API for detecting filetype-specific settings?

**Comment by kbd** [comment]
Just attempted to:

```
    "[plaintext]": {
        ...
        "rewrap.autoWrap.enabled": true,
    },
```

and it didn't work. I didn't even realize you couldn't specify settings like that per file-type. It would be wonderful if Rewrap could do this and save me a manual toggle each time. Thanks!

**Comment by stkb** [comment]
The next release will have the change many of you have been waiting for: `rewrap.autoWrap.enabled` can now be set per language.

Additionally, the `rewrap.toggleAutoWrap` command is still present, and can be used if you want to temporarily turn it on/off, but this is now a separate "**per-document** override" instead.

To help you keep track of when autowrap is on or off, there's a now a small (optional, but on by default) icon/notification in the right of the statusbar. This is controlled by the `rewrap.autoWrap.notification` setting, which currently has two options: `'icon' | 'text'`.

#### 'icon' (default)

This shows a small icon in the bottom right for the autowrap status of the current document. It actually has 4 states:
- <img height="20" src="https://user-images.githubusercontent.com/6125444/90771124-1bd38a00-e2f3-11ea-87bb-c625329b27b9.png"/> (normal): on, enabled in settings
- <img height="20" src="https://user-images.githubusercontent.com/6125444/90771558-c2b82600-e2f3-11ea-9a97-324a7960d978.png"/> (hidden): off, disabled in settings
- <img height="20" src="https://user-images.githubusercontent.com/6125444/90771573-c9469d80-e2f3-11ea-8b6e-e60c88dbe88f.png"/> (orange): temporarily enabled, from toggle command
- <img height="20" src="https://user-images.githubusercontent.com/6125444/90771602-d3689c00-e2f3-11ea-8e3b-5ae98bd6ba04.png"/> (gray): temporarily disabled, from toggle command

The icon's tooltip also gives some more information (will help with confusion like in #214)

Naturally not everyone wants an extra icon in their statusbar, so they can either [hide](https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items) it, or use the `text` option instead.

#### 'text'

There's also a 'text' notification option. This works almost the same as in the current version: it shows "Auto-wrap: on/off" for a few seconds when it's toggled on/off. But it now shows *only* when toggled. So if you never use that toggle command, you'll never see anything. (Fixes #144)

The [beta version is available to download](https://github.com/stkb/Rewrap/releases/tag/beta). Feedback is welcome!

I also haven't forgotten about a "full" auto-wrap setting (#65); it's still on my todo list.

**Comment by wevre** [comment]
Awesome Steve. Thanks for the hard work.

**Comment by max-sixty** [comment]
Could I ask whether the release referenced above was released? I don't see those options available.

Thank you for the excellent extension!

**Comment by stkb** [comment]
@max-sixty no it never got released. Coincidentally I've just started working on it again this week and it will be released in the next day or two. If you can't wait then you can still download & install the beta version above

**Comment by stkb** [comment]
v1.14.0 is now released! so closing
