### ISSUE TITLE
The 1.10.0 release doesn't wrap html anymore

### ISSUE THREAD

**Issue by stevehav** [stkb/Rewrap#192]
Upgrading to 1.10.1, I can no longer wrap html blocks.

A block like this:

`        <p>
            We want to change the world. With our powerful amazing software, you'll have one straightforward way to do everything in life you want.
        </p>
`

Under the previous version, 1.9.3, would wrap like this:

`        <p>
            We want to change the world. With our powerful amazing software,
            you'll have one straightforward way to do everything in life you
            want.
        </p>
`

Now it does nothing. I downgraded to 1.9.3 for now, which still works.

**Comment by stkb** [comment]
Just to confirm, you're using Visual Studio (not VSCode)? I ask because you mentioned v1.9.3, which was a VS-only release. v1.9.1 was the last VSCode release.

**Comment by asccc** [comment]
I have the same problem. Alt+Q does nothing.
VSCode 1.45.1

Apart from this, thank you very much for this awesome extension :)

**Comment by stkb** [comment]
@asccc Is it just html files that aren't working for you? Do other files work fine?

**Comment by asccc** [comment]
@stkb apparently, it stopped working completely.
I'll try to investigate if this was caused by a extension.

**Comment by asccc** [comment]
Sadly, rewrap does not work even with all other extensions disabled.

But i got a error message in the dev-tools now:
```
console.ts:137 [Extension Host] Rewrap: wrapping column is set at 'Object {column: 80}'. This will be treated as infinity.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

![grafik](https://user-images.githubusercontent.com/42143765/84433579-cd3cac00-ac2e-11ea-90f9-4ac208c5ed4b.png)


Maybe this is because the editor.rulers setting has changed some versions ago?
It now looks like this:

```json
"editor.rulers": [
    { "column": 80 },
    { "column": 100, "color": "#752828" }
],
```

**Comment by asccc** [comment]
Yep, this is related to the new extended "editor.rulers" setting and is fixed in https://github.com/stkb/Rewrap/pull/208

**Comment by stkb** [comment]
@asccc Thanks for the investigation! #208 has now been merged and the change is in [the latest beta](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by stkb** [comment]
However I don't think this was the cause of the original issue from @stevehav, because versions prior to v1.10.0 didn't support the new rulers either.

**Comment by eclipseo** [comment]
I have the same issue, tested the latest beta still not working, going back to 1.9.1 works.

**Comment by stkb** [comment]
@eclipseo It's just html that isn't working?

Can you try disabling all other extensions (`Disable All Installed Extensions` from the extensions sidebar menu, then re-enable Rewrap) then see if it makes a difference.

**Comment by eclipseo** [comment]
> @eclipseo It's just html that isn't working?
> 
No in my case I'm editing RPM Spec files.

> Can you try disabling all other extensions (`Disable All Installed Extensions` from the extensions sidebar menu, then re-enable Rewrap) then see if it makes a difference.

It works with everything else disabled. After enabling one by one, it turns out its the extension I use for linting RPM SPEC that is at fault: https://github.com/LaurentTreguier/vscode-rpm-spec So it might be a different issue than the one mentioned by OP.

**Comment by bbugh** [comment]
This is also happening with `.html.erb` files (ruby HTML templates). 😢

I am on version 1.13.0.

**Comment by bbugh** [comment]
@stkb it's this one: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

It worked in the past, but isn't any longer. Even with the extension disabled, it doesn't work, unfortunately.

**Comment by bbugh** [comment]
If it helps, the language is `erb` (which I believe is recognized by VSCode without any extensions) and the tmscope is `text.html.erb`

**Comment by stevehav** [comment]
I recently discovered that 1.14.0 also doesn't wrap HTML anymore. I'm using VS Code, installed the plugin via the VS code marketplace (so it should be the VS code not, not the visual studio one?), and the HTML wrap isn't working, the key combination does nothing in .cshtml files.

Downgraded to 1.9.1 and HTML wrapping is working, so I guess I will stay with 1.9.1 for the time being...
